using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public static class Names
{
    public static readonly string WALLS = "Walls";
    public static readonly string NOTES = "Notes";
    public static readonly string NOTE = "Note";
    public static readonly string PLANETS = "Planets";
    public static readonly string POSROTPLANET = "PosRotPlanet";
    public static readonly string ICECUBE = "IceCube";
    public static readonly string FLY = "fly";
    public static readonly string FLYALL = "flyAll";
    public static readonly string COLUMN = "Column";
    public static readonly string CENTERCOLUMN = "CenterColumn";
    public static readonly string KIKONGI = "Kikongi";
    public static readonly string MAILLOCHE = "Mailloche";
    public static readonly string SUN = "Sun";
    public static readonly string INDICATIONS = "Indications";
    public static readonly string SUNCOLLISION = "SunCollision";
    public static readonly string RECORDER = "Recorder"; 
    public static readonly string CIRCLERED = "CircleRed";
    public const string READ = "Read";
    public const string REC = "Rec";
    public const string STOP = "Stop";
    public const string ERASE = "Erase";
    public const string COUNTBALL = "CountBall"; // Minutes
    public const string MINUTE = "Minute";
    public static readonly string RED = "Red";
    public static readonly string GREEN = "Green";
    public static readonly string HEADPHONE = "Headphone";
    public static readonly string MUSIC = "Music";
    public static readonly string FLOOR = "Floor"; 
    public static readonly string JOUEUR = "Joueur";
    public static readonly string CHAKRA = "Chakra";
    public static readonly string ROCK = "Rock";
    public static readonly string NETPLANET = "NetPlanet";
    public static readonly string BUBBLERISE = "BubbleRise";
    public static readonly string BUBBLEDIE = "BubbleDie";
    public static readonly string WHALESONG = "WhaleSong";
    public static readonly string WHALEPOSITION = "WhalePosition";
    public static readonly string FISHESKIKONGI = "FishesKikongi";
    public static readonly string DOOROFPERCEPTION = "DoorOfPerception";
    public static readonly string PLAYER = "Player";
    public static readonly string FISHKIKONGI = "FishKikongi";
    public static readonly string DOLPHINPLAYZONE = "DolphinPlayZone";
    public static readonly string TRAUMA = "Trauma";
    public static readonly string GARBAGE = "Garbage";
    public static readonly string TRASHCAN = "TrashCan";
    public static readonly string ANIMAL = "Animal";
    public static readonly string HAND = "Hand";
    public static readonly string HANDLEFT = "HandLeft";
    public static readonly string HANDRIGHT = "HandRight";
    public static readonly string SEABED = "SeaBed";
    public static readonly string DYNAMITES = "Dynamites";
    public static readonly string NEPTUNE = "Neptune";
    public static readonly string HEART = "Heart";
    public static readonly string EMDR = "EMDR";
    public static readonly string FRACTALJOURNEY = "FractalJourney";
    public static readonly string FRACTAL = "Fractal";
}